workspace:
  base: /code

pipeline:
  build:
    image: node:12-alpine
    commands:
      - yarn
      - yarn run lint
      - yarn run test
      - yarn run build 
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]
